### ISSUE TITLE
InGame에서 Score가 적용되지 않는 오류 발생

### ISSUE THREAD

**Issue by csy-59** [strange-tiger/Running_Minigame_IG-2#30]
- 동전을 먹어도 점수가 오르지 않음

**Comment by strange-tiger** [comment]
- 재현 : 한 번 게임 오버를 하고 그 다음 게임부터 Score가 적용되지 않고 게임 오버 UI가 나오지 않는다.
- 예상 원인 : GameManager 같은 싱글톤이 적용된 오브젝트에서 위 사항을 관리하여, 별개 씬으로 넘어갔다가 다시 돌아오면 그런 문제가 발생된다고 예상된다.

**Comment by csy-59** [comment]
> 
싱글톤이 아닌 PlayerHeath에서 관리하는 사항입니다!

**Comment by csy-59** [comment]
- 해결: GameManager와 연결된 PlayerHealth가, 인게임에서 연결되는 과정에서 순서적 차이로 인한 오류였다.
관련 커밋: 30d8578ac0943fc584c8ff62ca568e76d27d662a
