### ISSUE TITLE
Sign In에서 Create Account를 연속으로 클릭할 수 있는 문제

### ISSUE THREAD

**Issue by csy-59** [strange-tiger/Running_Minigame_IG-2#31]

**Comment by strange-tiger** [comment]
성공적으로 계정을 생성하면 InputField가 비워지도록 코드 변경
-> 임시 해결

후에 기획서가 제대로 오면 관련 정보 패널이 표시되도록 변경 예정

**Comment by strange-tiger** [comment]
현재 기획서가 지연 중, 기능적으로는 해결되었으므로 Issue Close를 제안

**Comment by csy-59** [comment]
- 기획적인 문제, 기술적으로는 최대한 해결함
